
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      link: "mysql:direct_selling:OmZedRLkj39GuDlz@tcp(localhost:3306)/direct_selling?charset=utf8&parseTime=True&loc=Local"
      jsonCase: "CamelLower"