// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf/v2/util/gconv"

	"github.com/liuzhengtao/auth-common-backend/internal/consts"
	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
	"github.com/liuzhengtao/auth-common-backend/internal/model"
)

// internalSysMenuDao is internal type for wrapping internal DAO implements.
type internalSysMenuDao = *internal.SysMenuDao

// sysMenuDao is the data access object for table sys_menu.
// You can define custom methods on it to extend its functionality as you wish.
type sysMenuDao struct {
	internalSysMenuDao
}

var (
	// SysMenu is globally public accessible object for table sys_menu operations.
	SysMenu = sysMenuDao{
		internal.NewSysMenuDao("default"),
	}
)

//  Fill with you ideas below.

// ListRolePerms 获取角色权限
func (d *sysMenuDao) ListRolePerms(ctx context.Context, roles []string) (perms []string, err error) {
	orm := d.Ctx(ctx).As("t1").InnerJoin("sys_role_menu t2", "t1.id=t2.menu_id").InnerJoin("sys_role t3", "t3.id = t2.role_id").Fields("distinct t1.perm as perms").Where("t1.type", consts.BUTTON).Where("t1.perm IS NOT NULL")
	if len(roles) > 0 {
		orm = orm.WhereIn("t3.code", roles)
	} else {
		orm = orm.Where("t1.id", "-1")
	}
	result, err := orm.All()
	if err != nil {
		return nil, err
	}
	perms = make([]string, 0)
	for _, rowMap := range result.List() {
		perms = append(perms, gconv.String(rowMap["perms"]))
	}
	return
}

func (d *sysMenuDao) ListRoutes(ctx context.Context) (menuList []*model.RouteBO, err error) {
	err = d.Ctx(ctx).As("t1").LeftJoin("sys_role_menu t2", "t1.id=t2.menu_id").LeftJoin("sys_role t3", "t3.id = t2.role_id").Fields("t1.id,t1.name,t1.parent_id as parentId,t1.path,t1.component,t1.icon,t1.sort,t1.visible,t1.redirect,t1.type,t3.code as roles,t1.always_show as alwaysShow,t1.keep_alive as keepAlive").Where("t1.type != ?", consts.BUTTON).OrderAsc("t1.sort").Scan(&menuList)
	if err != nil {
		return nil, err
	}
	return
}
