// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf/v2/util/gconv"

	"github.com/liuzhengtao/auth-common-backend/internal/consts"
	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
	"github.com/liuzhengtao/auth-common-backend/internal/model"
)

// internalSysMenuDao is internal type for wrapping internal DAO implements.
type internalSysMenuDao = *internal.SysMenuDao

// sysMenuDao is the data access object for table sys_menu.
// You can define custom methods on it to extend its functionality as you wish.
type sysMenuDao struct {
	internalSysMenuDao
}

var (
	// SysMenu is globally public accessible object for table sys_menu operations.
	SysMenu = sysMenuDao{
		internal.NewSysMenuDao("default"),
	}
)

//  Fill with you ideas below.

// ListRolePerms 获取角色权限
func (d *sysMenuDao) ListRolePerms(ctx context.Context, roles []string) (perms []string, err error) {
	orm := d.Ctx(ctx).As("t1").InnerJoin("sys_role_menu t2", "t1.id=t2.menu_id").InnerJoin("sys_role t3", "t3.id = t2.role_id").Fields("distinct t1.perm as perms").Where("t1.type", consts.BUTTON).Where("t1.perm IS NOT NULL")
	if len(roles) > 0 {
		orm = orm.WhereIn("t3.code", roles)
	} else {
		orm = orm.Where("t1.id", "-1")
	}
	result, err := orm.All()
	if err != nil {
		return nil, err
	}
	perms = make([]string, 0)
	for _, rowMap := range result.List() {
		perms = append(perms, gconv.String(rowMap["perms"]))
	}
	return
}

func (d *sysMenuDao) ListRoutes(ctx context.Context) (menuList []*model.RouteBO, err error) {
	// JOIN 角色后同一菜单会多行；Roles 单行是角色 code 字符串，需按菜单 ID 合并后再建树。
	type routeRow struct {
		ID         int64  `json:"id"`
		ParentId   int64  `json:"parentId"`
		Name       string `json:"name"`
		Type       int    `json:"type"`
		Path       string `json:"path"`
		Component  string `json:"component"`
		Visible    int    `json:"visible"`
		Sort       int    `json:"sort"`
		Icon       string `json:"icon"`
		Redirect   string `json:"redirect"`
		Roles      string `json:"roles"`
		AlwaysShow int    `json:"alwaysShow"`
		KeepAlive  int    `json:"keepAlive"`
	}
	var rows []*routeRow
	err = d.Ctx(ctx).As("t1").LeftJoin("sys_role_menu t2", "t1.id=t2.menu_id").LeftJoin("sys_role t3", "t3.id = t2.role_id").Fields("t1.id,t1.name,t1.parent_id as parentId,t1.path,t1.component,t1.icon,t1.sort,t1.visible,t1.redirect,t1.type,t3.code as roles,t1.always_show as alwaysShow,t1.keep_alive as keepAlive").Where("t1.type != ?", consts.BUTTON).OrderAsc("t1.sort").Scan(&rows)
	if err != nil {
		return nil, err
	}
	merged := make(map[int64]*model.RouteBO, len(rows))
	order := make([]int64, 0, len(rows))
	for _, row := range rows {
		if exist, ok := merged[row.ID]; ok {
			if row.Roles != "" {
				exist.Roles = append(exist.Roles, row.Roles)
			}
			continue
		}
		roles := make([]string, 0, 1)
		if row.Roles != "" {
			roles = append(roles, row.Roles)
		}
		merged[row.ID] = &model.RouteBO{
			ID:         row.ID,
			ParentId:   row.ParentId,
			Name:       row.Name,
			Type:       row.Type,
			Path:       row.Path,
			Component:  row.Component,
			Visible:    row.Visible,
			Sort:       row.Sort,
			Icon:       row.Icon,
			Redirect:   row.Redirect,
			Roles:      roles,
			AlwaysShow: row.AlwaysShow,
			KeepAlive:  row.KeepAlive,
		}
		order = append(order, row.ID)
	}
	menuList = make([]*model.RouteBO, 0, len(order))
	for _, id := range order {
		menuList = append(menuList, merged[id])
	}
	return
}
