// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/liuzhengtao/auth-common-backend/api/v1/role"
	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
)

// internalSysRoleMenuDao is internal type for wrapping internal DAO implements.
type internalSysRoleMenuDao = *internal.SysRoleMenuDao

// sysRoleMenuDao is the data access object for table sys_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type sysRoleMenuDao struct {
	internalSysRoleMenuDao
}

var (
	// SysRoleMenu is globally public accessible object for table sys_role_menu operations.
	SysRoleMenu = sysRoleMenuDao{
		internal.NewSysRoleMenuDao("default"),
	}
)

// Fill with you ideas below.

func (d *sysRoleMenuDao) GetRolePermsList(ctx context.Context, roleCode string) (list []role.RolePermsBO, err error) {
	orm := d.Ctx(ctx).As("t1").InnerJoin("sys_role t2", "t1.role_id = t2.id and t2.deleted = 0 AND t2.`status` = 1").InnerJoin("sys_menu t3", "t1.menu_id = t3.id").Fields("t2.code as roleCode,t3.perm as perms")
	if len(roleCode) > 0 {
		orm = orm.Where("t2.code", roleCode)
	}
	err = orm.Scan(&list)
	return
}
