// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
	"github.com/liuzhengtao/auth-common-backend/internal/model/entity"
)

// internalSysDeptDao is internal type for wrapping internal DAO implements.
type internalSysDeptDao = *internal.SysDeptDao

// sysDeptDao is the data access object for table sys_dept.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeptDao struct {
	internalSysDeptDao
}

var (
	// SysDept is globally public accessible object for table sys_dept operations.
	SysDept = sysDeptDao{
		internal.NewSysDeptDao(),
	}
)

// Fill with you ideas below.

func (d *sysDeptDao) DeptOptionsList(ctx context.Context) (deptList []*entity.SysDept, err error) {
	err = d.Ctx(ctx).Fields("id,parent_id,name").OrderAsc("sort").Where("status", "1").Scan(&deptList)
	if err != nil {
		return nil, err
	}
	return
}
