// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/text/gstr"

	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
	"github.com/liuzhengtao/auth-common-backend/internal/model"
)

// internalSysUserDao is internal type for wrapping internal DAO implements.
type internalSysUserDao = *internal.SysUserDao

// sysUserDao is the data access object for table sys_user.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserDao struct {
	internalSysUserDao
}

var (
	// SysUser is globally public accessible object for table sys_user operations.
	SysUser = sysUserDao{
		internal.NewSysUserDao(),
	}
)

// Fill with you ideas below.

func (d *sysUserDao) ListPageUsers(ctx context.Context, userPage *model.UserPage, queryParams *model.UserPageQueryInput) error {
	orm := d.Ctx(ctx).As("u").LeftJoin("sys_dept d", "u.dept_id = d.id").LeftJoin("sys_user_role sur", "u.id = sur.user_id").LeftJoin("sys_role r", "sur.role_id = r.id").Fields(
		"u.id, u.username, u.nickname,u.mobile,u.gender,u.avatar,u.status,d.name as dept_name,group_concat(r.name) as role_names,u.create_time").Where("u.deleted=0 and u.username !='root'")
	if !gstr.Equal(queryParams.Keyword, "") {
		orm = (orm.Where(fmt.Sprintf("u.username like '%%%s%%'", queryParams.Keyword)).WhereOr(fmt.Sprintf("u.nickname like '%%%s%%'", queryParams.Keyword)).WhereOr(fmt.Sprintf("u.mobile like '%%%s%%'", queryParams.Keyword)))
	}
	if queryParams.Status != 4 {
		orm = orm.Where("u.status", queryParams.Status)
	}
	if queryParams.DeptId > 0 {
		orm = orm.Where("concat(',',concat(d.tree_path,',',d.id),',') like ?", fmt.Sprintf("%%,%d,%%", queryParams.DeptId))
	}
	if !gstr.Equal(queryParams.StartTime, "") {
		orm = orm.Where("u.create_time >= ?", queryParams.StartTime)
	}
	if !gstr.Equal(queryParams.EndTime, "") {
		orm = orm.Where("u.create_time <= ?", queryParams.EndTime)
	}
	result, total, err := orm.Group("u.id").Page(queryParams.PageNum, queryParams.PageSize).AllAndCount(false)
	if err != nil {
		return err
	}
	userPage.Total = total
	userPage.Records = make([]interface{}, 0)
	for _, v := range result.List() {
		userPage.Records = append(userPage.Records, v)
	}
	return nil
}

func (d *sysUserDao) GetUserAuthInfo(ctx context.Context, userName string) (authInfo *model.UserAuthInfo, err error) {
	err = d.Ctx(ctx).As("t1").LeftJoin("sys_user_role t2", "t1.id = t2.user_id").LeftJoin("sys_role t3", "t3.id = t2.role_id").Fields("t1.id as userId, t1.username, t1.nickname, t1.password,t1.dept_id,t3.code as roles").Where("t1.deleted=0 and username = ?",
		userName).Scan(&authInfo)
	if err != nil {
		return nil, err
	}
	return
}
