// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/text/gstr"

	"github.com/liuzhengtao/auth-common-backend/api/v1/role"
	"github.com/liuzhengtao/auth-common-backend/internal/consts"
	"github.com/liuzhengtao/auth-common-backend/internal/dao/internal"
	"github.com/liuzhengtao/auth-common-backend/internal/model"
)

// internalSysRoleDao is internal type for wrapping internal DAO implements.
type internalSysRoleDao = *internal.SysRoleDao

// sysRoleDao is the data access object for table sys_role.
// You can define custom methods on it to extend its functionality as you wish.
type sysRoleDao struct {
	internalSysRoleDao
}

var (
	// SysRole is globally public accessible object for table sys_role operations.
	SysRole = sysRoleDao{
		internal.NewSysRoleDao("default"),
	}
)

func (d *sysRoleDao) ListPage(ctx context.Context, req role.PageQueryReq, out *model.ListOutput) error {
	orm := d.Ctx(ctx)
	if !gstr.Equal(req.Keyword, "") {
		orm = orm.Where(fmt.Sprintf("name like '%%%s%%'", req.Keyword)).WhereOr(fmt.Sprintf("code like '%%%s%%'", req.Keyword))
	}
	orm = orm.WhereNot(d.Columns().Code, consts.ROOT_ROLE_CODE)
	result, total, err := orm.Page(req.PageNum, req.PageSize).OrderAsc("sort").AllAndCount(false)
	if err != nil {
		return err
	}
	out.List = result.List()
	out.Total = uint32(total)
	return nil
}
